server:
  port: 3344

spring:
  application:
    name: cloud-config-center  #注册进入Eureka服务器的服务
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hickey-lei/springcloud-config
          search-paths:
            - springcloud-config
      label: main
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'


